In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
resample = pd.read_csv('reample_csv')
print(resample.shape[0])

suc_data = pd.read_csv('suc_df_1768.csv')
print(suc_data.shape[0])

force_data = pd.read_csv('force_resampling.csv')
print(force_data.shape[0])

1768
1768
1768


#### `카이제곱 검정 (독립성 검정)`
- 두 변수는 서로 연관성이 있는가 없는가?
- 사진, 자기소개글, 가족소개글 업데이트 변수는 성혼과의 관련성이 있는가 없는가?

In [3]:
suc_data.columns

Index(['mem_no', 'mem_sex', 'mem_loc', 'mem_l_code', 'mem_birth_year',
       'mem_birth_month', 'mem_birth_ddi', 'mate_slct', 'mem_last_name_code',
       'rprsn_mov_yn', 'rprsn_photo_yn', 'photo_cnt', 'mate_job',
       'mate_ann_salary', 'mate_height', 'mate_weight', 'mate_blood',
       'mate_religion', 'mate_car', 'mate_career', 'mate_style', 'mate_charc',
       'mate_hobby', 'mate_offspring_m', 'mate_offspring_f', 'htown_loc',
       'htown_l_code', 'wed_plan', 'fashion_style', 'divorce_rslt',
       'brothers_sisters', 'possess_property', 'study_abroad', 'favor_food',
       'parents_slct', 'divorce_year', 'child_raise', 'smoke_slct',
       'drink_slct', 'health_slct', 'childbirth_slct', 'z_wish_age',
       'z_wish_loc', 'z_wish_religion', 'send_cnt', 'upd_cnt', 'conts_upd_cnt',
       'secret_item_yn', 'secret_yn', 'family_conts_upd_cnt', 'my_point_cont',
       'my_hd_item_yn', 'my_hd_yn', 'ins_date', 'upd_date', 'exit_date'],
      dtype='object')

In [4]:
upd_cnt_suc = suc_data[['upd_cnt','conts_upd_cnt','family_conts_upd_cnt']]
upd_cnt_suc

upd_cnt  conts_upd_cnt  family_conts_upd_cnt
0           7              4                     1
1           5              4                     0
2          45             19                     6
3           1              0                     0
4           4              2                     0
...       ...            ...                   ...
1763        2              0                     1
1764        1              0                     0
1765        6              1                     1
1766       13              5                     0
1767        9              2                     2

[1768 rows x 3 columns]

In [5]:
upd_cnt_suc.loc['sum',:] = upd_cnt_suc.sum()
upd_cnt_suc.loc['mean',:] = round(upd_cnt_suc.mean(),2)
upd_cnt_suc

C:\Users\PC\anaconda3\envs\tensor\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


upd_cnt  conts_upd_cnt  family_conts_upd_cnt
0         7.00            4.0                  1.00
1         5.00            4.0                  0.00
2        45.00           19.0                  6.00
3         1.00            0.0                  0.00
4         4.00            2.0                  0.00
...        ...            ...                   ...
1765      6.00            1.0                  1.00
1766     13.00            5.0                  0.00
1767      9.00            2.0                  2.00
sum   54531.00         9373.0               1925.00
mean     61.65           10.6                  2.18

[1770 rows x 3 columns]

In [6]:
upd_cnt_force = force_data[['upd_cnt','conts_upd_cnt','family_conts_upd_cnt']]
upd_cnt_force

upd_cnt  conts_upd_cnt  family_conts_upd_cnt
0           5              1                     0
1           1              0                     0
2           1              0                     0
3           1              0                     0
4           1              0                     0
...       ...            ...                   ...
1763       27              8                     1
1764        7              3                     0
1765        1              0                     0
1766        1              0                     0
1767        4              0                     0

[1768 rows x 3 columns]

In [7]:
upd_cnt_re = resample[['upd_cnt','conts_upd_cnt','family_conts_upd_cnt']]
upd_cnt_re

upd_cnt  conts_upd_cnt  family_conts_upd_cnt
0           1              0                     0
1           1              0                     0
2           2              0                     0
3           1              0                     0
4           1              0                     0
...       ...            ...                   ...
1763        1              0                     0
1764        1              0                     0
1765        3              0                     0
1766       14              3                     0
1767       12              3                     0

[1768 rows x 3 columns]

In [8]:
upd_cnt_force.loc['sum',:] = upd_cnt_force.sum()
upd_cnt_force.loc['mean',:] = round(upd_cnt_force.mean(),2)
upd_cnt_force

C:\Users\PC\anaconda3\envs\tensor\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


upd_cnt  conts_upd_cnt  family_conts_upd_cnt
0          5.00           1.00                  0.00
1          1.00           0.00                  0.00
2          1.00           0.00                  0.00
3          1.00           0.00                  0.00
4          1.00           0.00                  0.00
...         ...            ...                   ...
1765       1.00           0.00                  0.00
1766       1.00           0.00                  0.00
1767       4.00           0.00                  0.00
sum   142783.00       13051.00               2007.00
mean     161.43          14.76                  2.27

[1770 rows x 3 columns]

In [9]:
upd_cnt_force.sum()

upd_cnt                 285727.43
conts_upd_cnt            26116.76
family_conts_upd_cnt      4016.27
dtype: float64

In [10]:
upd_cnt_re.loc['sum',:] = upd_cnt_re.sum()
upd_cnt_re.loc['mean',:] = round(upd_cnt_re.mean(),2)
upd_cnt_re

C:\Users\PC\anaconda3\envs\tensor\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


upd_cnt  conts_upd_cnt  family_conts_upd_cnt
0         1.00           0.00                  0.00
1         1.00           0.00                  0.00
2         2.00           0.00                  0.00
3         1.00           0.00                  0.00
4         1.00           0.00                  0.00
...        ...            ...                   ...
1765      3.00           0.00                  0.00
1766     14.00           3.00                  0.00
1767     12.00           3.00                  0.00
sum   25322.00        8434.00               1655.00
mean     28.63           9.54                  1.87

[1770 rows x 3 columns]

`합계로 카이제곱 테스트`

In [11]:
chi_test_cnt = pd.DataFrame([upd_cnt_suc.loc['sum'].tolist(),upd_cnt_force.loc['sum'].tolist()],
                            columns = upd_cnt_force.columns, index=['suc','force'])
chi_test_cnt = chi_test_cnt.astype(int)
chi_test_cnt

upd_cnt  conts_upd_cnt  family_conts_upd_cnt
suc      54531           9373                  1925
force   142783          13051                  2007

In [12]:
chi_test_cnt2 = pd.DataFrame([upd_cnt_suc.loc['sum'].tolist(),upd_cnt_re.loc['sum'].tolist()],
                            columns = upd_cnt_re.columns, index=['suc','resample'])
chi_test_cnt2 = chi_test_cnt2.astype(int)
chi_test_cnt2

upd_cnt  conts_upd_cnt  family_conts_upd_cnt
suc         54531           9373                  1925
resample    25322           8434                  1655

- 귀무가설(H0) : 자기소개글 업데이트와 성혼간에는 관계가 없다.
- 대립가설(H1) : 자기소개글 업데이트와 성혼간에는 관계가 없다.

In [13]:
from scipy.stats import chi2_contingency
chi_2, p, dof, expected = chi2_contingency([chi_test_cnt.loc['suc'].values.tolist(),chi_test_cnt.loc['force'].values.tolist()])
msg = 'Test Statistic: {}\np-value: {}\nDegree of Freedom: {}'
print(msg.format(chi_2, p, dof))
print(expected)

Test Statistic: 2679.2348503483204
p-value: 0.0
Degree of Freedom: 2
[[ 58072.08524165   6599.67584388   1157.23891447]
 [139241.91475835  15824.32415612   2774.76108553]]


-> p-value 0.0으로 자기소개글 업데이트와 성혼간에는 관계가 있음?

In [14]:
from scipy.stats import chi2_contingency
chi_2, p, dof, expected = chi2_contingency([chi_test_cnt2.loc['suc'].values.tolist(),chi_test_cnt2.loc['resample'].values.tolist()])
msg = 'Test Statistic: {}\np-value: {}\nDegree of Freedom: {}'
print(msg.format(chi_2, p, dof))
print(expected)

Test Statistic: 1775.104586283677
p-value: 0.0
Degree of Freedom: 2
[[51922.59123864 11578.59544646  2327.8133149 ]
 [27930.40876136  6228.40455354  1252.1866851 ]]


일반이랑 차단 확인 좀 해보자

- 귀무가설 : 소개글 업데이트 수는 차단과의 관계가 없다
- 대립가설 : 소개글 업데이트 수는 차단과 관계가 있다

In [20]:
chi_test_cnt5 = pd.DataFrame([upd_cnt_re.loc['sum'].tolist(),upd_cnt_force.loc['sum'].tolist()],
                            columns = upd_cnt_force.columns, index=['resample','force'])
chi_test_cnt5 = chi_test_cnt5.astype(int)
chi_test_cnt5

upd_cnt  conts_upd_cnt  family_conts_upd_cnt
resample    25322           8434                  1655
force      142783          13051                  2007

In [22]:
from scipy.stats import chi2_contingency
chi_2, p, dof, expected = chi2_contingency([chi_test_cnt5.loc['resample'].values.tolist(),chi_test_cnt5.loc['force'].values.tolist()])
msg = 'Test Statistic: {}\np-value: {}\nDegree of Freedom: {}'
print(msg.format(chi_2, p, dof))
print(expected)

Test Statistic: 9250.438596858081
p-value: 0.0
Degree of Freedom: 2
[[ 30803.12832467   3936.8562033     671.01547203]
 [137301.87167533  17548.1437967    2990.98452797]]


`평균으로 카이제곱 테스트`

In [15]:
chi_test_cnt3 = pd.DataFrame([upd_cnt_suc.loc['mean'].tolist(),upd_cnt_force.loc['mean'].tolist()],
                            columns = upd_cnt_force.columns, index=['suc','force'])
chi_test_cnt3 = chi_test_cnt3.astype(int)
chi_test_cnt3

upd_cnt  conts_upd_cnt  family_conts_upd_cnt
suc         61             10                     2
force      161             14                     2

In [16]:
chi_2, p, dof, expected = chi2_contingency([chi_test_cnt3.loc['suc'].values.tolist(),chi_test_cnt3.loc['force'].values.tolist()])
msg = 'Test Statistic: {}\np-value: {}\nDegree of Freedom: {}'
print(msg.format(chi_2, p, dof))
print(expected)

Test Statistic: 2.9599485717433254
p-value: 0.2276435419638058
Degree of Freedom: 2
[[ 64.824   7.008   1.168]
 [157.176  16.992   2.832]]


In [17]:
chi_test_cnt4 = pd.DataFrame([upd_cnt_suc.loc['mean'].tolist(),upd_cnt_re.loc['mean'].tolist()],
                            columns = upd_cnt_force.columns, index=['suc','resample'])
chi_test_cnt4 = chi_test_cnt4.astype(int)
chi_test_cnt4

upd_cnt  conts_upd_cnt  family_conts_upd_cnt
suc            61             10                     2
resample       28              9                     1

In [18]:
chi_2, p, dof, expected = chi2_contingency([chi_test_cnt4.loc['suc'].values.tolist(),chi_test_cnt4.loc['resample'].values.tolist()])
msg = 'Test Statistic: {}\np-value: {}\nDegree of Freedom: {}'
print(msg.format(chi_2, p, dof))
print(expected)

Test Statistic: 1.7609657472423879
p-value: 0.41458267230405577
Degree of Freedom: 2
[[58.53153153 12.4954955   1.97297297]
 [30.46846847  6.5045045   1.02702703]]


In [23]:
chi_test_cnt6 = pd.DataFrame([upd_cnt_re.loc['mean'].tolist(),upd_cnt_force.loc['mean'].tolist()],
                            columns = upd_cnt_force.columns, index=['resample','force'])
chi_test_cnt6 = chi_test_cnt6.astype(int)
chi_test_cnt6

upd_cnt  conts_upd_cnt  family_conts_upd_cnt
resample       28              9                     1
force         161             14                     2

In [24]:
chi_2, p, dof, expected = chi2_contingency([chi_test_cnt6.loc['resample'].values.tolist(),chi_test_cnt6.loc['force'].values.tolist()])
msg = 'Test Statistic: {}\np-value: {}\nDegree of Freedom: {}'
print(msg.format(chi_2, p, dof))
print(expected)

Test Statistic: 8.844613854568735
p-value: 0.012006502183880942
Degree of Freedom: 2
[[ 33.40465116   4.06511628   0.53023256]
 [155.59534884  18.93488372   2.46976744]]
